"""empty message

Revision ID: 0c3998b7c432
Revises: fb0482aac942
Create Date: 2023-10-05 19:35:33.094154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3998b7c432'
down_revision = 'fb0482aac942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.alter_column('medicine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'])
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'])
        batch_op.alter_column('medicine_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
